### ISSUE TITLE
The link https://www.learnhowtoprogram.com/sections/spark is dead

### ISSUE THREAD

**Issue by tenzan** [sparktutorials/sparktutorials.github.io#10]
> ⚫ Beginner videos
> To follow the full course, go to https://www.learnhowtoprogram.com/sections/spark

**Comment by tipsy** [comment]
Thanks, seems they've restructured their website a bit... I'll have a lot at it later.

**Comment by tenzan** [comment]
Thanks, David!

**Comment by tipsy** [comment]
Fixed 5 bad links!
