### ISSUE TITLE
On the Chinese Disorder Code in the velocityTemplete

### ISSUE THREAD

**Issue by 602884291** [sparktutorials/sparktutorials.github.io#11]
I used spark-template-velocity as base,and edit velocity enviroments  DEFAUT-ENCODING 'OUTPUTENCODING' 'INPUT-ENCODING'  = UTF-8 ,but my static pages‘s chinese char is Disorder

**Comment by ftomassetti** [comment]
I am not sure I understand what do you mean. Are your static pages encoded with UTF-8?

**Comment by 602884291** [comment]
yes, my static pages already encoded with UTF-8, but thank you so much. I will countine resolve my problem.
