### ISSUE TITLE
Site is DOWN

### ISSUE THREAD

**Issue by facundofarias** [sparktutorials/sparktutorials.github.io#18]
For some reason, the site is DOWN:
![image](https://cloud.githubusercontent.com/assets/2700564/19799964/b7750d88-9cf9-11e6-83a1-1a59ce4d0553.png)

Any ideas?

**Comment by tipsy** [comment]
**You're** down.

(Really though, [site is up](http://downforeveryoneorjustme.com/sparktutorials.github.io/))
