### ISSUE TITLE
Consider adding disqus for comments

### ISSUE THREAD

**Issue by ftomassetti** [sparktutorials/sparktutorials.github.io#2]
If we want to activate comments we could add disqus (instructions are available here https://help.disqus.com/customer/portal/articles/472138-jekyll-installation-instructions).

Otherwise we could add a link to the forum or give some other directions to people that have problems with the tutorials or want to ask some advanced question.

**Comment by tipsy** [comment]
I added facebook/twitter/g+ share now, will have a look at disqus later :)

**Comment by tipsy** [comment]
Done!

**Comment by ftomassetti** [comment]
Cool, thanks!
