### ISSUE TITLE
The instructions for setting up spark with InteliJ are insufficient

### ISSUE THREAD

**Issue by oz123** [sparktutorials/sparktutorials.github.io#8]
(The title is true if you are new for InteliJ and Spark)

InteliJ is getting in my way, following the instructions I get the error:
```
Error:(8, 34) java: lambda expressions are not supported in -source 1.5
  (use -source 8 or higher to enable lambda expressions)
```

Even though I set the compiler options....
![screenshot-11](https://cloud.githubusercontent.com/assets/1083045/10188260/45a2a14c-675e-11e5-95f5-f323345cada2.png)

**Comment by oz123** [comment]
I have managed to solve this issue. It would probably be helpful for others to include the explanation in the tutorial. Here is how I solved it:

http://stackoverflow.com/questions/32861605/enable-lambda-expression-in-java-8-in-intelij?noredirect=1#comment53556099_32861605

**Comment by tipsy** [comment]
I've added the following parahraph:

If IntelliJ says *"Method references are not supported at this language level"*,
press *alt+enter* and choose *"Set language level to 8 - Lambdas, type annotations, etc."*.
