### ISSUE TITLE
Please document how to autorestart jetty\spark after uncought exception

### ISSUE THREAD

**Issue by oz123** [sparktutorials/sparktutorials.github.io#9]
Once my application encounters an exception which is uncaught it crashes mercilessly. 
How do I restart it without pressisg CTL+C and re-running the mvn command?

**Comment by tipsy** [comment]
Hi @oz123, are you referring to a specific tutorial, or do you mean Spark in general?

**Comment by oz123** [comment]
I was thinking more in general. But it seems that when an exception is thrown in one of the threads, it still accepts request. I was thinking that is not the case with spark.
